# GoReleaser configuration for Cronic
# Documentation: https://goreleaser.com

version: 2

project_name: cronic

# Build configuration
builds:
  - id: cronic
    main: ./cmd/cronic
    binary: cronic
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "7" # For ARMv7 if needed
    flags:
      - -trimpath
    ldflags:
      - -X github.com/hzerrad/cronic/internal/cmd.version={{.Version}}
      - -X github.com/hzerrad/cronic/internal/cmd.commit={{.Commit}}
      - -X github.com/hzerrad/cronic/internal/cmd.date={{.Date}}
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows

# Archive configuration
archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md
    formats:
      - tar.gz

# Checksums
checksum:
  name_template: "checksums.txt"
  algorithm: sha256

# Snapshots (for development/testing)
snapshot:
  # name_template removed - using default snapshot naming

# Changelog
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

# Homebrew tap configuration
# Note: brews is deprecated but still works. For CLI tools, brews is still the correct section.
brews:
  - name: cronic
    repository:
      owner: hzerrad
      name: homebrew-cronic
    homepage: https://github.com/hzerrad/cronic
    description: Make cron human again - CLI tool for cron job management
    license: Apache-2.0
    test: |
      system "#{bin}/cronic", "version"
    install: |
      bin.install "cronic"
    dependencies:
      - go
    commit_author:
      name: goreleaserbot
      email: goreleaser@cronic.dev

# APT (Debian/Ubuntu) repository configuration
nfpms:
  - id: deb
    package_name: cronic
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: hzerrad
    homepage: https://github.com/hzerrad/cronic
    maintainer: hzerrad <contact@hzerrad.dev>
    description: Make cron human again - CLI tool for cron job management
    license: Apache-2.0
    formats:
      - deb
    bindir: /usr/bin
    contents:
      - src: LICENSE
        dst: /usr/share/doc/cronic/copyright
      - src: README.md
        dst: /usr/share/doc/cronic/README.md

  - id: rpm
    package_name: cronic
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: hzerrad
    homepage: https://github.com/hzerrad/cronic
    maintainer: hzerrad <contact@hzerrad.dev>
    description: Make cron human again - CLI tool for cron job management
    license: Apache-2.0
    formats:
      - rpm
    bindir: /usr/bin
    contents:
      - src: LICENSE
        dst: /usr/share/doc/cronic/LICENSE
      - src: README.md
        dst: /usr/share/doc/cronic/README.md
    rpm:
      group: Applications/System
      compression: gzip
      summary: Make cron human again - CLI tool for cron job management

# Release configuration
release:
  github:
    owner: hzerrad
    name: cronic
  mode: replace
  header: |
    ## Cronic {{ .Tag }}
    
    {{ .ReleaseNotes }}
    
    ### Installation
    
    #### Homebrew
    ```bash
    brew tap hzerrad/cronic
    brew install cronic
    ```
    
    #### APT (Debian/Ubuntu)
    ```bash
    wget https://github.com/hzerrad/cronic/releases/download/{{ .Tag }}/cronic_{{ .Tag }}_amd64.deb
    sudo dpkg -i cronic_{{ .Tag }}_amd64.deb
    ```
    
    #### DNF/YUM (Fedora/RHEL)
    ```bash
    wget https://github.com/hzerrad/cronic/releases/download/{{ .Tag }}/cronic-{{ .Tag }}-1.x86_64.rpm
    sudo dnf install cronic-{{ .Tag }}-1.x86_64.rpm
