# GoReleaser configuration for Cronkit
# Documentation: https://goreleaser.com
version: 2

project_name: cronkit

builds:
  - id: cronkit
    main: ./cmd/cronkit
    binary: cronkit
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -X github.com/hzerrad/cronkit/internal/cmd.version={{ .Version }}
      - -X github.com/hzerrad/cronkit/internal/cmd.commit={{ .Commit }}
      - -X github.com/hzerrad/cronkit/internal/cmd.date={{ .Date }}
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot: {}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

# Homebrew formula (tap: hzerrad/homebrew-cronkit -> brew tap hzerrad/cronkit)
brews:
  - name: cronkit
    homepage: https://github.com/hzerrad/cronkit
    description: Make cron human again - CLI tool for cron job management
    license: Apache-2.0

    # Ensure formula downloads the correct release asset
    url_template: "https://github.com/hzerrad/cronkit/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    # Ensure GoReleaser writes the formula where taps expect it
    directory: Formula

    repository:
      owner: hzerrad
      name: homebrew-cronkit
      # Use a PAT that has write access to hzerrad/homebrew-cronkit
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    install: |
      bin.install "cronkit"
    test: |
      system "#{bin}/cronkit", "version"

    commit_author:
      name: goreleaserbot
      email: goreleaser@cronkit.dev

# AUR (Arch User Repository)
aurs:
  - name: cronkit-bin
    homepage: https://github.com/hzerrad/cronkit
    description: Make cron human again - CLI tool for cron job management
    license: Apache-2.0
    maintainers:
      - hzerrad <contact@hzerrad.dev>

    git_url: "ssh://aur@aur.archlinux.org/cronkit-bin.git"

    private_key: "{{ .Env.AUR_SSH_PRIVATE_KEY }}"

    provides:
      - cronkit
    conflicts:
      - cronkit

    package: |
      install -Dm755 "./cronkit" "${pkgdir}/usr/bin/cronkit"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/cronkit/LICENSE"
      install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/cronkit/README.md"

# DEB/RPM packages
nfpms:
  - id: deb
    package_name: cronkit
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: hzerrad
    homepage: https://github.com/hzerrad/cronkit
    maintainer: hzerrad <contact@hzerrad.dev>
    description: Make cron human again - CLI tool for cron job management
    license: Apache-2.0
    formats:
      - deb
    bindir: /usr/bin
    contents:
      - src: LICENSE
        dst: /usr/share/doc/cronkit/copyright
      - src: README.md
        dst: /usr/share/doc/cronkit/README.md

  - id: rpm
    package_name: cronkit
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: hzerrad
    homepage: https://github.com/hzerrad/cronkit
    maintainer: hzerrad <contact@hzerrad.dev>
    description: Make cron human again - CLI tool for cron job management
    license: Apache-2.0
    formats:
      - rpm
    bindir: /usr/bin
    contents:
      - src: LICENSE
        dst: /usr/share/doc/cronkit/LICENSE
      - src: README.md
        dst: /usr/share/doc/cronkit/README.md
    rpm:
      group: Applications/System
      compression: gzip
      summary: Make cron human again - CLI tool for cron job management

release:
  github:
    owner: hzerrad
    name: cronkit
  mode: replace
  header: |
    ## Cronkit {{ .Tag }}

    {{ .ReleaseNotes }}

    ### Installation

    #### Homebrew
    ```bash
    brew tap hzerrad/cronkit
    brew install cronkit
    ```

    #### APT (Debian/Ubuntu)
    ```bash
    wget https://github.com/hzerrad/cronkit/releases/download/{{ .Tag }}/cronkit_{{ .Version }}_linux_amd64.deb
    sudo dpkg -i cronkit_{{ .Version }}_linux_amd64.deb
    ```

    #### DNF/YUM (Fedora/RHEL)
    ```bash
    wget https://github.com/hzerrad/cronkit/releases/download/{{ .Tag }}/cronkit_{{ .Version }}_linux_amd64.rpm
    sudo dnf install cronkit_{{ .Version }}_linux_amd64.rpm
    ```

    #### Pacman/AUR (Arch Linux)
    ```bash
    yay -S cronkit-bin
    # or
    paru -S cronkit-bin
    ```